general:
  # index is used in combination with port_offset to auto-generate a port forwarding for all used ports in order to run multiple iom environments in parallel
  index : 0
  # port_offset is used in combination with index to auto-generate a port forwarding for all used ports in order to run multiple iom environments in parallel
  port_offset : 10
  #timezone is used to set the timezone for the containers(e.g. database) (default: Europe/Berlin)
  timezone : Europe/Berlin

docker:

database:
  db_name : infinity_db
  db_user : infinity_user
  db_password : infinity_pw


raincoat: 1
coins: 5
books: 23
spectacles: 2
chairs: 12
pens: 6

foo: 
  bar: 'bar'
sports:

  - soccer
  - football
  - basketball
  - cricket
  - hockey
  - table tennis